servers:
  web:
    hosts:
      - one.work
  job:
    hosts:
      - one.work
env:
  clear:
    HOST: one.work
    ASSET_HOST: assets.work.design

accessories:
  postgres:
    host: one.work

proxy:
  hosts:
    - one.work
    - '*.one.work'
    - '*.admin.one.work'
  ssl:
    certificate_path: /certs/one.work.pem
    private_key_path: /certs/one.work.key