servers:
  web:
    hosts:
      - one.work
  job:
    hosts:
      - one.work
env:
  clear:
    ASSET_HOST: assets.work.design
accessories:
  postgres:
    host: one.work
proxy:
  hosts:
    - one.work
  ssl: true